### 错误处理

Go使用一个独立、明确的返回值来传递错误信息

```go
func test(arg int) (int, error) {
	if arg == 42 {
		return -1, errors.New("cant work with 42")
	} else {
		return arg + 1, nil
	}
}

func main() {
	//常见的错误检查用法
	for _, i := range []int{7, 42} {
		if r, e := test(i); e != nil {
			fmt.Println("test failed")
		} else {
			fmt.Println("test worked", r)
		}
	}
}
```

也可以通过实现Error()方法，自定义error类型的结构体



### Panic

标识我们不想优雅的处理错误

输出错误信息，并以非零的状态退出程序



### Defer

保证了我们在执行完函数执行完毕后，调用某个清理工作

类似finally，不过要在panic()之前使用defer关键字声明好

**Exit**

`os.Exit` 可以立即以给定的状态退出程序， `defer` 将不会被执行

```go
func main() {
    defer fmt.Println("defer!")
    os.Exit(3)
}
//exit status 3
```



### Recover

必须在 defer 函数中调用 `recover`

当panic()发生defer被激活时，recover会捕获panic，并在执行完毕后结束程序

